CREATE DATABASE Projeto_Individual;

USE Projeto_Individual;

CREATE TABLE Usuario (
    ID_Usuario INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(100) NOT NULL UNIQUE,
    Telefone CHAR(14) NOT NULL UNIQUE,
    CPF CHAR(11) NOT NULL UNIQUE,
    Senha VARCHAR(100) NOT NULL
) 	AUTO_INCREMENT = 1000;

CREATE TABLE Endereco (
    ID_Endereco INT PRIMARY KEY AUTO_INCREMENT,
    Estado VARCHAR(100) NOT NULL,
    Cidade VARCHAR(100) NOT NULL,
    Bairro VARCHAR(100) NOT NULL,
    FK_Usuario INT NOT NULL,
    FOREIGN KEY (FK_Usuario) REFERENCES Usuario(ID_Usuario)
);

CREATE TABLE Cartas (
    ID_Carta INT PRIMARY KEY AUTO_INCREMENT,
    Nome VARCHAR(100) NOT NULL,
    Classificacao VARCHAR(20) NOT NULL,
    Descricao_Classificacao VARCHAR(100) NOT NULL,
    Qualidade VARCHAR(100) NOT NULL,
    Descricao VARCHAR(300) NOT NULL,
    FK_Usuario INT NOT NULL,
    FOREIGN KEY (FK_Usuario) REFERENCES Usuario(ID_Usuario)
);
